# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c71f1a0583281fa836950f824d3f78d314c27f57cbe11ecf03523ee17978502e335c96cc834792966614b73724fd510523c8771638423f260df4e5eb16595e4

test:
  secret_key_base: 287820273c60bc50d19acd11adefca33354a62011ae1ee10018c44398ebd4a4aed7d9a2e3d3f14baa39a23cb14951e316a1059212afd620fd10a5acccb11ee45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
